import {
    ArrowLeftOutlined,
    EyeInvisibleOutlined,
    EyeTwoTone,
} from "@ant-design/icons";
import { Input } from "antd";
import { useState } from "react";
import { toast } from "sonner";
import { https_authupdate } from "../../service/api";

export default function ChangePassword({ onBack }) {

    const [current, setCurrent] = useState("");
    const [newPw, setNewPw] = useState("");
    const [confirm, setConfirm] = useState("");
    const [totp, setTotp] = useState("");
    const [requireTotp, setRequireTotp] = useState(false);


    const handleChangePassword = async () => {
        if (!current || !newPw || !confirm) {
            return toast.error("Please fill in all fields.");
        }

        if (newPw.length < 6) {
            return toast.error("New password must be at least 6 characters.");
        }

        if (newPw !== confirm) {
            return toast.error("New passwords do not match.");
        }

        // Nếu backend đã yêu cầu OTP thì mới validate
        if (requireTotp) {
            if (!totp) {
                return toast.error("Please enter your 2FA authentication code.");
            }

            if (!/^\d{6}$/.test(totp)) {
                return toast.error("2FA code must be a 6-digit number.");
            }
        }

        try {
            await https_authupdate.patch("/v1/update-password", {
                oldPassword: current,
                newPassword: newPw,
                ...(requireTotp && { totp: Number(totp) }),
            });

            toast.success("Password updated successfully!");

            setCurrent("");
            setNewPw("");
            setConfirm("");
            setTotp("");
            setRequireTotp(false);

        } catch (err) {
            const code = err?.response?.data?.code;
            const msg = err?.response?.data?.message;

            // ✅ Backend yêu cầu 2FA
            if (code === "SYS-AUTH-029") {
                setRequireTotp(true);
                return toast.info("Please enter your 2FA authentication code.");
            }

            toast.error(msg || "Failed to update password.");
        }
    };


    return (
        <div className="text-gray-700">
            {/* HEADER */}
            <div className="flex items-center gap-3 mb-8">
                <button onClick={onBack} className="p-1 rounded hover:bg-gray-200">
                    <ArrowLeftOutlined />
                </button>
                <h2 className="text-xl font-semibold">Change password</h2>
            </div>

            {/* CURRENT PASSWORD */}
            <div className="mb-6">
                <h3 className="text-sm font-medium mb-1">Current password</h3>
                <Input.Password
                    value={current}
                    onChange={(e) => setCurrent(e.target.value)}
                    className="w-80"
                    iconRender={(v) => v ? <EyeTwoTone /> : <EyeInvisibleOutlined />}
                />
            </div>

            {/* NEW PASSWORD */}
            <div className="mb-6">
                <h3 className="text-sm font-medium mb-1">New password</h3>
                <Input.Password
                    value={newPw}
                    onChange={(e) => setNewPw(e.target.value)}
                    className="w-80"
                    iconRender={(v) => v ? <EyeTwoTone /> : <EyeInvisibleOutlined />}
                />
            </div>

            {/* CONFIRM PASSWORD */}
            <div className="mb-6">
                <h3 className="text-sm font-medium mb-1">Confirm new password</h3>
                <Input.Password
                    value={confirm}
                    onChange={(e) => setConfirm(e.target.value)}
                    className="w-80"
                    iconRender={(v) => v ? <EyeTwoTone /> : <EyeInvisibleOutlined />}
                />
            </div>

            {/* ✅ TOTP INPUT – chỉ hiện khi backend yêu cầu */}
            {requireTotp && (
                <div className="mb-6">
                    <h3 className="text-sm font-medium mb-1">
                        2FA authentication code
                    </h3>

                    <Input
                        value={totp}
                        onChange={(e) => setTotp(e.target.value)}
                        placeholder="Enter 6-digit code"
                        maxLength={6}
                        className="w-40"
                        autoFocus
                    />

                    <p className="text-xs text-gray-500 mt-1">
                        Enter the 6-digit code generated by your authenticator app
                        (Google Authenticator, Microsoft Authenticator, Authy, etc.).
                    </p>
                </div>
            )}



            {/* FOOTER */}
            <div className="flex justify-end gap-3 pr-3">
                <button
                    onClick={onBack}
                    className="px-4 py-1.5 rounded border text-sm hover:bg-gray-100"
                >
                    Cancel
                </button>

                <button
                    onClick={handleChangePassword}
                    className="px-4 py-1.5 rounded bg-[#f8b4a0] text-white text-sm hover:bg-[#f7a58d]"
                >
                    Change password
                </button>
            </div>
        </div>
    );
}
