# -----------------------
# 1?? App Config
# -----------------------
server.port=9999
jwt.secret=${JWT_SECRET}

# -----------------------
# 2?? OAuth2 Google (Production)
# -----------------------
spring.security.oauth2.client.registration.google.client-id=817537515968-93s63ioe6uamvj8ii5nnspke2kp341dj.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=https://yourdomain.com/api/auth/login/oauth2/code/google

# -----------------------
# 3?? Database (Production)
# -----------------------
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# -----------------------
# 4?? Redis (Production)
# -----------------------
spring.redis.host=${REDIS_HOST}
spring.redis.port=${REDIS_PORT}
spring.redis.password=${REDIS_PASSWORD}

# -----------------------
# 5?? Email (Production)
# -----------------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=automaticemail0204@gmail.com
spring.mail.password=lztz vkly edwe sucl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# -----------------------
# 6?? Kafka (Production)
# -----------------------
spring.kafka.bootstrap-servers=${KAFKA_SERVERS}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=5

app.kafka.topic.auth.register-email=auth.notification.register-email.v1
app.kafka.topic.auth.reset-password-email=auth.notification.reset-password-email.v1
app.kafka.topic.auth.update-email=auth.notification.update-email.v1

# -----------------------
# 7?? Logging
# -----------------------
logging.level.root=INFO
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
