# -----------------------
# 1?? Th�ng tin ?ng d?ng
# -----------------------
spring.application.name=taskflow-service
spring.profiles.active=dev
server.servlet.context-path=/api/taskflow
# -----------------------
# 2?? JPA & Jackson
# -----------------------
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh
spring.jackson.time-zone=Asia/Ho_Chi_Minh
# -----------------------
# 3?? C?u h�nh Pagination
# -----------------------
# Default page size
spring.data.web.pageable.default-page-size=5
# Start page from 1 (instead of 0)
spring.data.web.pageable.one-indexed-parameters=true
# Parameter name
spring.data.web.pageable.page-parameter=pageNumber
spring.data.web.pageable.size-parameter=pageSize
spring.data.web.sort.sort-parameter=sort
# -----------------------
# 4?? C?u h�nh Exception Handling
# -----------------------
spring.mvc.throw-exception-if-no-handler-found=true
spring.mvc.static-path-pattern=/swagger*
# -----------------------
# 5?? Swagger
# -----------------------
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
# -----------------------
# 7?? Cau hinh AWS
# -----------------------
cloud.aws.region.static=ap-southeast-1
aws.s3.bucket-name=aws-todoist
# -----------------------
# 8?? Cau hinh upload file
# -----------------------
spring.servlet.multipart.max-file-size=3MB
spring.servlet.multipart.max-request-size=3MB
# -----------------------
# Frontend config
# -----------------------
frontend.base-url=http://localhost:3000
# -----------------------
# Invite config
# -----------------------
invite.path=/invite
invite.ttl-minutes=15
