# -----------------------
# 1?? Th�ng tin ?ng d?ng
# -----------------------
spring.application.name=user-service
spring.profiles.active=dev-docker
server.servlet.context-path=/api/user

# -----------------------
# 2?? JPA & Jackson
# -----------------------
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh
spring.jackson.time-zone=Asia/Ho_Chi_Minh

# -----------------------
# 3?? Pagination
# -----------------------
spring.data.web.pageable.default-page-size=5
spring.data.web.pageable.one-indexed-parameters=true
spring.data.web.pageable.page-parameter=pageNumber
spring.data.web.pageable.size-parameter=pageSize
spring.data.web.sort.sort-parameter=sort

# -----------------------
# 4?? Exception Handling
# -----------------------
spring.mvc.throw-exception-if-no-handler-found=true
spring.mvc.static-path-pattern=/swagger*

# -----------------------
# 5?? Swagger (m?c ??nh t?t)
# -----------------------
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
